config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "application#home", as: "home"
  get '/search/', to: "application#search", as: "search_movie"
  get '/discover/', to: "application#home", as: "discover"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :init

  @@language_map = {:en => "en-US"}

  def home
    result = @client.discover @current_page_number
    @cached = result[:cached]
    result = result[:result]
    if result
      @movies = result["results"]
    end
  end

  def search
    @searched_query = params[:search_query]
    result = @client.search @searched_query, @current_page_number
    @cached = result[:cached]
    result = result[:result]
    if result
      @movies = result["results"]
      @total_pages = result["total_pages"]
      @total_results = result["total_results"]
    end
  end

  def init
    @client = MoviesClient.new
    @current_page_number = params[:page].present? ? params[:page].to_i : 1
    @genres = @client.get_genres(@@language_map[I18n.locale])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_poster_image(image_path, title)
    if image_path.present?
      image_tag "#{BASE_IMAGE_PATH}t/p/w154#{image_path}", class: "image-size", alt: title
    else
      image_tag "default-poster.jpg", alt: title
    end
  end

  def get_start_interval
    @current_page_number < 5 ? 1 : @current_page_number - 3
  end

  def get_end_interval
    @total_pages.blank? || @current_page_number + 3 < @total_pages ? @current_page_number + 3 : @total_pages
  end

  def page_navigation_path(path, page_number)
    method(path).call(:search_query => params[:search_query], :page => page_number)
  end

  def genres ids
    ids.map do |id|
      @genres[id]
    end.join(", ")
  end

end

app/views/application/_search_form.html.erb
<%= form_with url: search_movie_path, method: :get do |form| %>
  <%= form.text_field :search_query, class: "form-control search-bar", placeholder: I18n.t("search_placeholder"), value: @searched_query, :required => true %>
  <%= form.submit I18n.t("search"), class: "btn btn-outline-primary me-2 search-button" %>
<% end %>

app/views/application/_search_results.html.erb
<div class="search-results">
  <% @movies&.each do |movie| %>
    <div class="movie-card">
      <%= get_poster_image movie["poster_path"], movie["title"] %>
      <span class="info"><%= I18n.t("title") %></span>
      <%= label_tag(nil, truncate(movie["title"], :length => 20), class: "info-data", title: movie["title"], 'data-toggle' => 'tooltip', 'data-placement' => 'right') %>
      <br>
      <span class="info"><%= I18n.t("release_date") %></span>
      <span class="info-data"> <%= movie["release_date"].present? ? DateTime.parse(movie["release_date"]).strftime("%d %b %Y") : ""%> </span>
      <br>
      <span class="info"><%= I18n.t("genre") %></span>
      <%= label_tag(nil, truncate(genres(movie["genre_ids"]), :length => 20), class: "info-data", title: genres(movie["genre_ids"]), 'data-toggle' => 'tooltip', 'data-placement' => 'right') %>
    </div>
  <% end %>
</div>

<% if @total_pages.blank? || @total_pages > 1 %>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

      <li class="page-item <%= @current_page_number == 1 ? "disabled" : "" %>">
        <%= link_to "<", page_navigation_path(:search_movie_path, @current_page_number - 1), class: "page-link" %>
      </li>

      <% (get_start_interval..get_end_interval).to_a.each do |number| %>
        <li class="page-item <%= number == @current_page_number ? "active" : "" %>">
          <%= link_to number, page_navigation_path(path, number), class: "page-link" %>
        </li>
      <% end %>

      <% if @total_pages.present? %>
        <li class="page-item <%= @current_page_number == @total_pages ? "disabled" : "" %>">
          <%= link_to ">", page_navigation_path(path, @current_page_number + 1), class: "page-link" %>
      <% end %>
    </ul>
  </nav>
<% end %>

<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

app/views/application/home.html.erb
<% if @cached %>
  <div class="alert alert-warning flash-message" role="alert">
    <span>
      <%= I18n.t("cached_notification") %>
    </span>
  </div>
<% end %>

<div class="search-form">
  <%= render partial: "search_form" %>
</div>

<div id="search_results">
  <%= render partial: "search_results", locals: { :path => :discover_path } %>
</div>

app/views/application/search.html.erb
<% if @cached %>
  <div class="alert alert-warning flash-message" role="alert">
    <span>
      <%= I18n.t("cached_notification") %>
    </span>
  </div>
<% end %>

<div class="search-form">
  <%= render partial: "search_form" %>
</div>

<div id="search_results">
  <%= render partial: "search_results", locals: { :path => :search_movie_path } %>
</div>

app/views/application/search_form.js.erb
$("#search_form").html("<%= escape_javascript(render partial: 'search_form') %>");

app/views/application/search_result.js.erb
$("#search_results").html("<%= escape_javascript(render partial: 'search_results') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviesDatabase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="wrapper">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>